language: python

python:
- '2.7'
- '3.6'
- '3.7'

sudo: false

env:
  PYTHONPATH: lib

install:
- pip install -r requirements.txt

script:
- pylint lib/*.py
- kodi-addon-checker . --branch=gotham
- kodi-addon-checker . --branch=helix
- kodi-addon-checker . --branch=isengard
- kodi-addon-checker . --branch=jarvis
- kodi-addon-checker . --branch=krypton
- kodi-addon-checker . --branch=leia
- pytest lib/tests.py
